### ISSUE TITLE
Crashing when listening on a socket

### ISSUE THREAD

**Issue by kmzijadev** [kazuho/p5-Server-Starter#27] opened 2015-06-01 18:46 UTC
Here is a trace from a cluck('') thrown right before the error (plus the error itself):

 at /usr/local/lib/perl/5.18.2/Socket.pm line 823.
    Socket::sockaddr_in("\x{1}\x{0}/var/run/starman/megaoff.sock\x{0}") called at /usr/lib/perl/5.18/IO/Socket/INET.pm line 270
    IO::Socket::INET::sockaddr(Net::Server::Proto::TCP=GLOB(0xdc46960)) called at /usr/lib/perl/5.18/IO/Socket/INET.pm line 283
    IO::Socket::INET::sockhost(Net::Server::Proto::TCP=GLOB(0xdc46960)) called at /usr/share/perl5/Net/Server.pm line 522
    Net::Server::get_client_info(Starman::Server=HASH(0xdbddbc0), Net::Server::Proto::TCP=GLOB(0xdc46960)) called at /usr/share/perl5/Net/Server.pm lin
e 71
    Net::Server::run_client_connection(Starman::Server=HASH(0xdbddbc0)) called at /usr/share/perl5/Net/Server/PreFork.pm line 229
    eval {...} called at /usr/share/perl5/Net/Server/PreFork.pm line 229
    Net::Server::PreFork::run_child(Starman::Server=HASH(0xdbddbc0)) called at /usr/share/perl5/Net/Server/PreFork.pm line 187
    Net::Server::PreFork::run_n_children(Starman::Server=HASH(0xdbddbc0), 30) called at /usr/share/perl5/Net/Server/PreFork.pm line 111
    Net::Server::PreFork::loop(Starman::Server=HASH(0xdbddbc0)) called at /usr/share/perl5/Net/Server.pm line 61
    Net::Server::run(Starman::Server=HASH(0xdbddbc0), "port", ARRAY(0xdace458), "host", "*", "proto", "tcp", "serialize", "none", ...) called at /usr/s
hare/perl5/Starman/Server.pm line 84
    Starman::Server::run(Starman::Server=HASH(0xdbddbc0), CODE(0xc8e66e8), HASH(0xd8948a0)) called at /usr/share/perl5/Plack/Handler/Starman.pm line 18
    Plack::Handler::Starman::run(Plack::Handler::Starman=HASH(0xc3ee700), CODE(0xc8e66e8)) called at /usr/share/perl5/Plack/Loader.pm line 84
    Plack::Loader::run(Plack::Loader=HASH(0xc8a4d0), Plack::Handler::Starman=HASH(0xc3ee700)) called at /usr/share/perl5/Plack/Runner.pm line 277
    Plack::Runner::run(Plack::Runner=HASH(0x966cb8)) called at /usr/bin/starman line 38
Bad arg length for Socket::unpack_sockaddr_in, length is 32, should be 16 at /usr/local/lib/perl/5.18.2/Socket.pm line 831.

start_server was invoked thus: start_server --interval 5 --signal-on-term=QUIT --signal-on-hup=QUIT --path=$SOCKFILE --dir=$RUNDIR --pid-file=$PIDFILE --status-file=$STATFILE -- starman --workers 30 --error-log $LOGFILE --preload-app $APPFILE

**Comment by kazuho** [comment] 2015-06-01 20:00
@kmzijadev This is likely a bug in Starman (or in Net::Server that Starman depends on).

`Socket::unpack_sockaddr_in` should not be called with a `sockaddr_un` argument, which is obviously the cause of the issue looking at:
> Socket::sockaddr_in("\x{1}\x{0}/var/run/starman/megaoff.sock\x{0}") called at /usr/lib/perl/5.18/IO/Socket/INET.pm line 270

**Comment by nagata-logly** [comment] 2016-04-05 06:22
I have same error. When I use Starman and Server::Starter.
But When I use only Starman. It's can work by unix socket.

Cc @miyagawa

```
Bad arg length for Socket::unpack_sockaddr_in, length is 24, should be 16 at /home/hoge/perl5/perlbrew/perls/perl-5.16.0/lib/5.16.0/x86_64-linux/Socket.pm line 780.
```



### work

```
starman --listen /tmp/hoge.sock hoge.psgi
```

### not work

```
start_server --path=/tmp/hoge.sock -- \
starman hoge.psgi
```

- Net::Server Version: 2.008
- Starman Version: 0.4014
- Server::Starter Version: 0.32

**Comment by nagata-logly** [comment] 2016-04-05 06:36
and ...
When I use Starlet and Server::Starter.
It's can work by unix socket.

**Comment by nagata-logly** [comment] 2016-04-05 08:11
I find debug message here.
When I use Starman with Server::Starter.

```
start_server (pid:13457) starting now...
starting new worker 13471
Setting gid to "10 10 10"
Starman: Accepting connections at http://0:5000/
```

When I use only Starman.

```
2016/04/05-16:49:57 Starman::Server (type Net::Server::PreFork) starting! pid(30079)
Binding to UNIX socket file "/tmp/hoge.sock"
Setting gid to "10 10 10"
Starman: Accepting connections at unix://localhost:/tmp/hoge.sock/
```
somthing wrong...

**Comment by kazuho** [comment] 2016-04-05 17:45
@nagata-logly (cc @miyagawa)
I can at least say is that @kmzijadev's case is not an issue of Server::Starter.  Please see https://github.com/kazuho/p5-Server-Starter/issues/27#issuecomment-107690024.

Therefore I am closing the issue now - I would suggest reporting the issue to Starman.  Or please reopen the issue in case it turns out that what you are seeing is different from the original case.

**Closed by kazuho** 2016-04-05 17:45 UTC

**Comment by miyagawa** [comment] 2016-04-06 04:53
The error seems to come from Net::Server::PreFork - which is a superclass of Net::Server::SS::PreFork.

```
Starting "1" children
Bad arg length for Socket::unpack_sockaddr_in, length is 106, should be 16 at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/darwin-2level/Socket.pm line 831.
	Socket::sockaddr_in("j\x{1}/tmp/backend.sock\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}"...) called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/5.20.1/darwin-2level/IO/Socket/INET.pm line 271
	IO::Socket::INET::sockaddr(Net::Server::Proto::TCP=GLOB(0x7ffa32309168)) called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/5.20.1/darwin-2level/IO/Socket/INET.pm line 284
	IO::Socket::INET::sockhost(Net::Server::Proto::TCP=GLOB(0x7ffa32309168)) called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/Net/Server.pm line 521
	Net::Server::get_client_info(Starman::Server=HASH(0x7ffa32103690), Net::Server::Proto::TCP=GLOB(0x7ffa32309168)) called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/Net/Server.pm line 70
	Net::Server::run_client_connection(Starman::Server=HASH(0x7ffa32103690)) called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/Net/Server/PreFork.pm line 229
	eval {...} called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/Net/Server/PreFork.pm line 229
	Net::Server::PreFork::run_child(Starman::Server=HASH(0x7ffa32103690)) called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/Net/Server/PreFork.pm line 187
	Net::Server::PreFork::run_n_children(Starman::Server=HASH(0x7ffa32103690), 5) called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/Net/Server/PreFork.pm line 111
	Net::Server::PreFork::loop(Starman::Server=HASH(0x7ffa32103690)) called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/Net/Server.pm line 60
	Net::Server::run(Starman::Server=HASH(0x7ffa32103690), "port", ARRAY(0x7ffa319669c8), "host", "*", "proto", "tcp", "serialize", ...) called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/Starman/Server.pm line 94
	Starman::Server::run(Starman::Server=HASH(0x7ffa32103690), CODE(0x7ffa321033f0), HASH(0x7ffa31994908)) called at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/Plack/Handler/Starman.pm line 25
```

**Comment by kazuho** [comment] 2016-04-06 05:14
@miyagawa Thank you for looking into it.

Net::Server::SS::PreFork!  I have long forgotten of writing such a module.  It's not even on GitHub!  Will look into it.
